name: ci
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version.version }}

      - run: pip install -r <(grep ^flake8 requirements.txt)

      - run: make lint

  test:
    strategy:
      matrix:
        python_version:
          - version: "3.7"
            env: py37
          - version: "3.8"
            env: py38
          - version: "3.9"
            env: py39
          - version: "3.10"
            env: py310

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version.version }}

      - run: pip install -r <(grep ^tox requirements.txt)

      - run: tox -e ${{ matrix.python_version.env }}
